type ConfigKeysType = 'PORT' | 'GIT_COMMIT' | 'HOSTNAME' | 'BLOG_CONNECTION_STRING'
export const CONFIG_KEYS: { [Key in ConfigKeysType]: Key } = {
  PORT: 'PORT',
  GIT_COMMIT: 'GIT_COMMIT',
  HOSTNAME: 'HOSTNAME',
  BLOG_CONNECTION_STRING: 'BLOG_CONNECTION_STRING'
}
